version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:80"
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: microservices
      DB_USER: postgres
      DB_PASSWORD: bikeshop
  db:
    image: postgres
    environment:
      POSTGRES_DB: microservices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bikeshop
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    volumes:
      - C:/Users/Pepik/git/app/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"