name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint
      run: |
        pylint **/*.py

    - name: Run unit tests
      run: |
        python -m unittest test.py

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/grafana:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}



    - name: Create Kubernetes manifests directory on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
          mkdir -p home/ubuntu/kubernetes/manifests
        EOF
    - name: List files in repository
      run: |
        ls -l

    - name: Upload Kubernetes manifests to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./flask-app-deployment.yaml ./flask-app-service.yaml ./postgres-deployment.yaml ./postgres-service.yaml ./prometheus-deployment.yaml ./prometheus-service.yaml ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }}:home/ubuntu/kubernetes/manifests

    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -t ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
          # Pull and run Docker image
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/grafana:latest
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker run -d -p 80:80 -p 3000:3000 -p 9090:9090 --name my-app ${{ secrets.DOCKER_USERNAME }}/grafana:latest
          # Set up kubectl
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        EOF

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config


    - name: Apply Kubernetes manifests
      run: |
        ssh -o StrictHostKeyChecking=no -t ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
          kubectl apply -f $HOME/kubernetes/manifests/flask-app-deployment.yaml --validate=false
          kubectl apply -f $HOME/kubernetes/manifests/flask-app-service.yaml
          kubectl apply -f $HOME/kubernetes/manifests/postgres-deployment.yaml
          kubectl apply -f $HOME/kubernetes/manifests/postgres-service.yaml
          kubectl apply -f $HOME/kubernetes/manifests/prometheus-deployment.yaml
          kubectl apply -f $HOME/kubernetes/manifests/prometheus-service.yaml
        EOF
