name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pylint
      run: |
        pylint **/*.py
    - name: Run unit tests
      run: |
        python -m unittest test.py


  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/grafana:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

#    - name: Deploy Docker image to EC2
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
#          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/grafana:latest
#          sudo docker stop my-app || true
#          sudo docker rm my-app || true
#          sudo docker run -d -p 80:80 -p 3000:3000 -p 9090:9090 --name my-app ${{ secrets.DOCKER_USERNAME }}/grafana:latest
#        EOF
    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
          # Pull and run Docker image
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/grafana:latest
          sudo docker stop my-app || true
          sudo docker rm my-app || true
          sudo docker run -d -p 80:80 -p 3000:3000 -p 9090:9090 --name my-app ${{ secrets.DOCKER_USERNAME }}/grafana:latest
          # Set up kubectl
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        EOF

#    - name: Set up kubectl
#      uses: azure/setup-kubectl@v1
#      with:
#        kubectl-version: 'latest'

#    - name: Create .kube directory
#      run: mkdir -p $HOME/.kube

#    - name: Configure kubectl
#      run: |
#        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
#    - name: Configure Kubeconfig for Minikube
#      run: |
#        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
#          mkdir -p $HOME/.kube
#          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
#        EOF
#
#    - name: List files
#      run: ls -R
    - name: List files on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
          ls -R
        EOF

    - name: Apply Kubernetes manifests
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'  
          kubectl apply -f flask-app-deployment.yaml --validate=false
          kubectl apply -f flask-app-service.yaml
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f postgres-service.yaml
          kubectl apply -f prometheus-deployment.yaml
          kubectl apply -f prometheus-service.yaml
        EOF